name: edutainstem
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  blurrycontainer: ^2.1.0
  change_app_package_name: ^1.5.0
  choice: ^2.3.2
  cloud_firestore: ^6.0.1
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  duration_picker: ^1.2.0
  easy_stepper: ^0.8.5+1
  expandable: ^5.0.1
  fancy_password_field: ^2.0.8
  file_saver: ^0.3.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_gen_runner: ^5.10.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_time_picker_spinner: ^2.0.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  giffy_dialog: ^2.3.0
  glass_kit: ^4.0.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hugeicons: ^1.1.0
  json_annotation: ^4.9.0
  mesh_gradient: ^1.3.8
  motion: ^2.0.1
  percent_indicator: ^4.2.5
  pluto_grid: ^8.0.0
  qr_flutter: ^4.1.0
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  sidebarx: ^0.17.1
  skeletonizer: ^2.1.0+1
  uuid: ^4.5.1
  wheel_slider: ^1.2.2

dev_dependencies:
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0

flutter_gen:
  output: lib/core/gen/

  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/png/
    - assets/images/logo/
    - assets/lottie/
