name: edutainstem
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  animations: ^2.0.11
  blurrycontainer: ^2.1.0
  change_app_package_name: ^1.5.0
  easy_stepper: ^0.8.5+1
  fancy_password_field: ^2.0.8
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen_runner: ^5.10.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  glass_kit: ^4.0.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  mesh_gradient: ^1.3.8
  motion: ^2.0.1
  pluto_grid: ^8.0.0
  sidebarx: ^0.17.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0

flutter_gen:
  output: lib/core/gen/

  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/png/
    - assets/images/logo/
